revise pinning nixpkgs WIP
NixOS/nix.dev pull request #303
Opened 2022-08-11 13:23 UTC by olafklingt

remove pinning nixpkgs reference
separate pinning nixpkgs from dependency management using niv

2022-08-11 13:26 UTC, olafklingt commented
I have read the CLA Document and I hereby sign the CLA

2022-08-11 13:26 UTC, olafklingt commented
recheck

2022-08-11 18:39 UTC, olafklingt commented
After writing ["I keep a note for myself that the “pinning reference” needs some work."](https://discourse.nixos.org/t/pinning-nixpkgs-in-documentation-examples/20749/7) i made this draft today. It is mostly based on nix.dev material written by @domenkozar I would like to know if you agree this PR is going into right direction (as outlined by @fricklerhandwerk ).

2022-08-19 14:57 UTC, infinisil requested changes

2022-08-20 10:58 UTC, olafklingt commented on source/tutorials/pinning-nixpkgs.md
> +Possible `URL` values are:
We can write `URL` or `path`

2022-08-20 10:59 UTC, olafklingt commented on source/tutorials/pinning-nixpkgs.md
> +- Using latest channel, meaning all tests have passed: `http://nixos.org/channels/nixos-21.05/nixexprs.tar.xz`
thanks for pointing out

2022-08-20 11:09 UTC, olafklingt commented on source/tutorials/pinning-nixpkgs.md
> +- Using latest channel, meaning all tests have passed: `http://nixos.org/channels/nixos-21.05/nixexprs.tar.xz`
which are not equivalent? 

commit tar.gz and nixos tar.gz ?

or 

nixos.org and github.com tar.gz that are referring to a release?

2023-11-13 22:01 UTC, closed without merging