Documentation section
NixOS/nix.dev pull request #384
Opened 2022-11-07 18:19 UTC by yukiisbored

2022-11-07 19:46 UTC, fricklerhandwerk approved these changes

2022-12-07 23:05 UTC, fricklerhandwerk requested changes
Sorry for stalling this for so long, and also that you have to rebase lots of things. This page still needs much work, but that's a great start. Let's merge this soon.

2022-12-08 18:40 UTC, yukiisbored commented on source/index.md
> +documentation/index.md
It seems Sphinx isn't happy when a page isn't included in a `toctree`

```
b"\nWarning, treated as error:\n/home/yuki/src/github.com/nixos/nix.dev/source/contributing-documentation.md:document isn't included in any toctree\nmake: *** [Makefile:53: html] Error 2\n"
```

What if we make contributing a category with its content on the top-level and contributing documentation as a child of the new category?

2022-12-10 03:22 UTC, fricklerhandwerk commented on source/index.md
> +documentation/index.md
Perfect!

2022-12-16 07:31 UTC, fricklerhandwerk approved these changes

2022-12-16 07:32 UTC, merged