Make code blocks consistent
NixOS/nix.dev pull request #390
Opened 2022-11-08 16:39 UTC by yukiisbored

Illustration of shell sessions or terminals should use shell-session.

Entire expressions should be encapsulated in code blocks, not inline code.

2022-11-08 17:45 UTC, fricklerhandwerk requested changes
In general I strongly agree that this should be made consistent, but I have a few general objections:

If we prepend $ to every command line, one has to manually select only the relevant part. Each code block has a copy button which IIRC take the whole string. Even if it's improbably smart for shell-session, those who for whatever reason don't find or use it will still have that problem. I would rather keep it consistent without the prompt. You'll notice that then many things stop working as they were originally layed out, such as the Nix shell prompts. I have no answer for that yet.

For the input output pairs I and quite certain: no, please keep them as in the Nix language tutorial. It has advantages for reading the source, and once highlighting works properly output can be nicely distinguished in rendering. See [this comment on a similar issue](https://github.com/NixOS/nixos-summer/pull/41#discussion_r953222745) for details.

Also I've seen people discuss it in other contexts and would like to adopt it for us to avoid descriptions of examples within code comments. Prose should be prose, code should be code, and there should be as little code as possible, because it's always a cognitive burden to read unfamiliar code.

Suggestion: change it to be consistent according to my proposal, and leave it as it is where it's not easy or obvious what to do.

2022-11-11 17:23 UTC, yukiisbored commented
@fricklerhandwerk 

> If we prepend $ to every command line, one has to manually select only the relevant part. 

`shell-session` makes the prompt unselectable as it uses the `gp` CSS class which sets `user-select` to `none`.

Here's a GIF which demonstrates me trying to highlight and copy-paste code from various snippets:
![2022-11-11_18-16-49](https://user-images.githubusercontent.com/18437312/201394245-be2e4270-b5cb-4887-99a2-e80ff825a68e.gif)

> Each code block has a copy button which IIRC take the whole string. Even if it's improbably smart for shell-session, those who for whatever reason don't find or use it will still have that problem.

The copy button with `shell-session` copies only the first line without the prompt and as demonstrated before, `shell-session` makes prompt unselectable.

> I would rather keep it consistent without the prompt. You'll notice that then many things stop working as they were originally layed out, such as the Nix shell prompts. I have no answer for that yet.

nix-shell prompts works fine as the lexer which detects the prompt takes that into account: https://pygments.org/docs/terminal-sessions/

If anything, this goes to show how https://github.com/NixOS/nix.dev/issues/385 is important as we don't use GitHub Flavored Markdown to render them.

2022-11-12 09:47 UTC, fricklerhandwerk approved these changes
@yukiisbored you convinced me, I shut up. 🙂

2022-11-12 09:47 UTC, merged

2022-11-25 10:57 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-40/23480/1