Correction in calling functions section
NixOS/nix.dev pull request #402
Opened 2022-11-25 21:57 UTC by henrik-ch

List elements separated by white space
examples were not generating correctly.

2022-11-25 21:58 UTC, henrik-ch commented
I have read the CLA Document and I hereby sign the CLA

2022-11-25 23:01 UTC, fricklerhandwerk requested changes
Good catch, thanks!

Only the indentation was wrong. The idea was to distinguish the output code block by making it non-highlighted. (CSS to show a different background color is still not working unfortunately...)

2022-11-25 23:01 UTC, fricklerhandwerk commented on source/tutorials/nix-language.md
> +```
```suggestion
    [ <LAMBDA> 1 ]
```

2022-11-25 23:01 UTC, fricklerhandwerk commented on source/tutorials/nix-language.md
> +```
```suggestion
    [ 2 ]
```

2022-11-25 23:41 UTC, henrik-ch commented
Hi Valentin,
Firstly, thank you for your patience. This is pretty much my first pull request ever.

The web tool didn't allow me to include the changes that you suggested. Therefore, I "remade" those same changes on the branch. I hopefully got it correct. I also hope and think that these changes propagated correctly into this pull request from the branch.

2022-11-26 00:22 UTC, fricklerhandwerk approved these changes
Hi Henrik, welcome to the party then!

Don't worry:
- small PRs are the best
- knowledge is unevenly distributed
- everyone makes mistakes

The point of reviews is to share knowledge and ensure everyone understands the code. 

Thanks for *your* patience, because feedback on PRs has no ETA.

2022-11-26 00:24 UTC, merged