Comment about display problems and fix with older kernel
NixOS/nix.dev pull request #415
Opened 2022-12-10 09:12 UTC by mmolhoek

Comment about display problems and fix with older kernel

PS: now from its own branch....sry

2022-12-10 09:30 UTC, mmolhoek commented
I have read the CLA Document and I hereby sign the CLA

2022-12-10 10:45 UTC, fricklerhandwerk requested changes
Thanks for the fix! Please fix the errors though. We try to establish a high standard of quality to improve Nix's reputation with regard to documentation.

Please also consider the [contribution guides](https://nix.dev/contributing#contribute-to-documentation), where all of that is detailed. I'll be happy to take feedback if these guides are approachable and helpful to make high quality changes with reasonable effort.

2022-12-10 10:45 UTC, fricklerhandwerk commented on source/tutorials/installing-nixos-on-a-raspberry-pi.md
> +There have been reported [some problems](https://github.com/NixOS/nixpkgs/issues/179701) with the latest sd images on the pi 4, where it turns of the display while booting up.
```suggestion

There have been reported [some problems](https://github.com/NixOS/nixpkgs/issues/179701) with the latest SD images on the Pi 4, where it turns off the display while booting up.
```

Open a new paragraph for each topic. Lumping everything together makes the text harder to scan and parse, and most readers don't actually read.

Please run basic spell check before submitting PRs. Use the official spelling of product names.

2022-12-10 10:45 UTC, fricklerhandwerk commented on source/tutorials/installing-nixos-on-a-raspberry-pi.md
> +If you are experiencing such problems, please use [this image](https://hydra.nixos.org/build/134720986/download/1/nixos-sd-image-21.03pre262561.581232454fd-aarch64-linux.img.zst) instead until it is
```suggestion
If you are experiencing such problems, please use [the most recent working build](https://hydra.nixos.org/build/134720986/download/1/nixos-sd-image-21.03pre262561.581232454fd-aarch64-linux.img.zst) instead until the issue is fixed.
```

Name links in a way that is self-explanatory. The link should be readable in isolation. 

Also in general, don't just point people to "this random-sounding thing", that doesn't exactly inspire confidence and requires additional scrutiny. Make evident why this is the correct approach to follow. In this case it's only a matter of telling what it is you're pointing to.

2022-12-13 11:24 UTC, merged

2022-12-23 10:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-42/24204/1