Add myself (pstn) as member.
NixOS/nix.dev pull request #474
Opened 2023-03-17 10:50 UTC by pstn

Ping @infinisil

2023-03-17 11:05 UTC, pstn commented
Is this a bug that my markdown doesn't get rendered correctly, or am I overlooking something?

2023-03-17 13:47 UTC, infinisil requested changes

2023-03-17 13:47 UTC, infinisil commented on maintainers/README.md
> +- [Philipp](httsp://github.com/pstn)
```suggestion
- [Philipp](https://github.com/pstn)
```

:smile:

2023-03-17 17:20 UTC, merged

2023-03-19 18:33 UTC, pstn commented on maintainers/README.md
> +- [Philipp](httsp://github.com/pstn)
Oh...

2023-04-02 01:15 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/this-month-in-nix-docs-1-march-2023/26913/1