Update nix-language.md
NixOS/nix.dev pull request #506
Opened 2023-04-01 18:49 UTC by lxnn

I added information about what `import` does if you give it the path to a directory rather than a file.

I think, without this information, the meaning of `import <nixpkgs>` in the next section isn't clear. I was a little bit confused by it.

2023-04-02 00:43 UTC, fricklerhandwerk commented
It's much more complicated than that: https://nixos.org/manual/nix/unstable/language/builtins.html#builtins-import

But this is not the place to unwrap that complexity. The question is why you got confused: did you know otherwise beforehand, or did it mislead you into believing wrong things?

2023-04-06 21:35 UTC, infinisil commented
I don't think this has to be complicated. This is a small change pointing out something non-obvious but often-used.

2023-04-06 21:36 UTC, infinisil requested changes

2023-04-06 21:36 UTC, infinisil commented on source/tutorials/nix-language.md
> +`import` takes a path to a Nix file, reads it to evaluate the contained Nix expression, and returns the resulting value. If the path is a directory, the file `default.nix` in that directory is read.
```suggestion
`import` takes a path to a Nix file, reads it to evaluate the contained Nix expression, and returns the resulting value.
If the path points to a directory, the file `default.nix` in that directory is used instead.
```

2023-04-06 21:44 UTC, merged

2023-05-05 19:54 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/this-month-in-nix-docs-2-april-2023/27899/1