Add contributing to Nixpkgs tutorial
NixOS/nix.dev pull request #696
Opened 2023-08-24 22:56 UTC by proofconstruction

While writing *Packaging Existing Software with Nix*, I originally had a section at the end where the reader is walked through preparing the package for submission to Nixpkgs. This is a cleaned-up version of that which maintains continuity with the other tutorial, and should help get people contributing faster.

There is a lot more to be said on this topic, but probably all of *that* belongs in a recipe instead.

2023-08-26 06:12 UTC, zmitchell requested changes
Generally I think you can cut down how much of this is rehashing the previous tutorial, but other than that I'm a fan of the content.

I think this belongs in the learning journey section given that it's a direct follow up to the learning journey tutorial it refers to.

2023-08-26 06:12 UTC, zmitchell commented on source/tutorials/contributing-to-nixpkgs.md
> +The package is now ready for submission to Nixpkgs!
You should try running the package first :)

2023-08-26 18:57 UTC, yukiisbored commented on source/tutorials/contributing-to-nixpkgs.md
> +In this tutorial, which follows {ref}`the tutorial on packaging existing software <packaging-existing-software>`, you will learn how to prepare newly-packaged software for submission to Nixpkgs, beco
Unlike links, this uses the `packaging-existing-software` reference and will work no matter where it is placed in the file system as long as the reference exists somewhere.

2023-09-11 16:36 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/2023-09-11-documentation-team-meeting-notes-79/32917/1

2023-09-12 01:52 UTC, infinisil requested changes

2023-09-12 01:52 UTC, infinisil commented on source/tutorials/contributing-to-nixpkgs.md
> +There are currently two other similar tools already in `nixpkgs`, both of which are stored in `pkgs/applications/graphics`, so this is a good candidate for a home for `icat` too.
You should use [`pkgs/by-name`](https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#readme) for new packages now! No need to edit `all-packages.nix` either that way :)

2023-09-12 01:52 UTC, infinisil commented on source/tutorials/contributing-to-nixpkgs.md
> +Before contributing your first package, you *must* add your information to [`nixpkgs/maintainers/maintainers-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix),
This is a better docs link: https://github.com/NixOS/nixpkgs/tree/master/maintainers#readme

2023-11-20 15:01 UTC, bzm3r reviewed
I like it! I learned just from reading the PR, so yeah, it would be really nice to have this on nix.dev!

I think the changes suggested by @infinisil and @zmitchell are quite useful. So, once those get merged....

2023-11-20 15:07 UTC, bzm3r commented on source/tutorials/contributing-to-nixpkgs.md
> +3. Use `nix-prefetch-url` or a similar tool to fetch, unpack, and hash the files marked by the tag or release you selected.
Yes! I strongly agree with this.

2023-12-03 01:24 UTC, infinisil commented
@bzm3r Since the original author seems busy, could you create a new PR taking the feedback into account?

2024-01-08 17:36 UTC, proofconstruction commented
Decided in [this comment](https://github.com/NixOS/nix.dev/pull/831#issuecomment-1879545180) to close this and merge anything useful into the `CONTRIBUTING.md` in nixpkgs, etc.

2024-01-08 17:36 UTC, closed without merging